name: check

on: [push, pull_request]
#  push:
#    paths:
#      - "trombinoscope/staff/**"
      
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
jobs:
  yaml_checks:
    # avoid to run twice push and PR
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get the code
        uses: actions/checkout@v2

      - name: Install tools
        run: 'sudo apt-get install yamllint imagemagick'

      - name: Run check scripts
        run: 'fail=0;
              for p in .github/workflows/check_scripts/*.sh; do
                echo "==> $p";
                "$p" || fail=1;
              done;
              exit "$fail"'
